cart/urls.py
from django.urls import path
from cart import views

app_name = 'cart'
urlpatterns = [
    path('add/<int:id>', views.AddToCartView.as_view(), name='add'),
    path('delete/<str:un_id>', views.DeleteFromView.as_view(), name='delete'),
    path('', views.CartDetailView.as_view(), name='cart'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('products/', include('product.urls')),
    path('cart/', include('cart.urls')),
    path('', include('home.urls'))
] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models
from product.models import Product

class Cart:

    def __new__(cls, *args, **kwargs):
        return super().__new__(cls)

    def __init__(self, request):
        self.session = request.session
        self.cart = self.session.get('cart')
        if not self.cart:
            self.cart = self.session['cart'] = dict()

    def __iter__(self):
        cart = self.cart
        for i in cart.values():
            i['product'] = un_id = Product.objects.get(pk=int(i['id']))
            i['total'] = (int(i['quantity']) * float(i['price']))
            i['un_id'] = self.unique_id_generator(id=un_id.id, color=i['color'])
            if 0 < float(i['discount']):
                i['per_object_total'] = (
                    i['total'] - ((float(i['total']) - float(i['discount'])) / 100)
                )
            yield i

    def add(self, product, quantity, color):
        unique = self.unique_id_generator(id=product.id, color=color)
        if not unique in self.cart:
            self.cart[unique] = dict({
                'id': str(product.id),
                'price': str(product.price),
                'discount': str(product.discount),
                'color':color,
                'quantity': int(quantity),
            })
            self.save()
        else:
            self.cart[unique]['quantity'] += int(quantity)
            self.save()

    def delete(self, un_id):
        if self.cart[un_id]:
            del self.cart[un_id]
            self.save()

    def remove_cart(self):
        del self.session['cart']

    def save(self):
        self.session.modified = True

    @staticmethod
    def unique_id_generator(id, color):
        return f"{id}{color}"

cart/views.py
from django.shortcuts import render, redirect
from django.views.generic.detail import DetailView
from django.views.generic import View
from cart.models import *
from product.models import Product

class CartDetailView(View):
    template_name = 'cart/cart.html'

    def get(self, request):
        cart = Cart(self.request)
        return render(request, self.template_name, context={'cart':cart})


class AddToCartView(View):

    def post(self, request, id):
        product = Product.objects.get(pk=id)
        quantity, color = self.request.POST.get('quantity'), self.request.POST.get('color')
        print(quantity, color, product.title)
        Cart(self.request).add(product, quantity, color)
        return redirect('product:detail', product.slug)


class DeleteFromView(View):

    def get(self, request, un_id):
        Cart(self.request).delete(un_id=un_id)
        return redirect('cart:cart')

cart/templates/cart/cart.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %} {{ request.resolver_match.url_name }} {% endblock %}
{% block content %}

	<!-- Cart -->
	<div class="wrap-header-cart js-panel-cart">
		<div class="s-full js-hide-cart"></div>

		<div class="header-cart flex-col-l p-l-65 p-r-25">
			<div class="header-cart-title flex-w flex-sb-m p-b-8">
				<span class="mtext-103 cl2">
					Your Cart
				</span>

				<div class="fs-35 lh-10 cl2 p-lr-5 pointer hov-cl1 trans-04 js-hide-cart">
					<i class="zmdi zmdi-close"></i>
				</div>
			</div>
			
			<div class="header-cart-content flex-w js-pscroll">
				<ul class="header-cart-wrapitem w-full">
					<li class="header-cart-item flex-w flex-t m-b-12">
						<div class="header-cart-item-img">
							<img src="{% static 'images/item-cart-01.jpg' %}" alt="IMG">
						</div>

						<div class="header-cart-item-txt p-t-8">
							<a href="#" class="header-cart-item-name m-b-18 hov-cl1 trans-04">
								White Shirt Pleat
							</a>

							<span class="header-cart-item-info">
								1 x $19.00
							</span>
						</div>
					</li>

					<li class="header-cart-item flex-w flex-t m-b-12">
						<div class="header-cart-item-img">
							<img src="{% static 'images/item-cart-02.jpg' %}" alt="IMG">
						</div>

						<div class="header-cart-item-txt p-t-8">
							<a href="#" class="header-cart-item-name m-b-18 hov-cl1 trans-04">
								Converse All Star
							</a>

							<span class="header-cart-item-info">
								1 x $39.00
							</span>
						</div>
					</li>

					<li class="header-cart-item flex-w flex-t m-b-12">
						<div class="header-cart-item-img">
							<img src="{% static 'images/item-cart-03.jpg' %}" alt="IMG">
						</div>

						<div class="header-cart-item-txt p-t-8">
							<a href="#" class="header-cart-item-name m-b-18 hov-cl1 trans-04">
								Nixon Porter Leather
							</a>

							<span class="header-cart-item-info">
								1 x $17.00
							</span>
						</div>
					</li>
				</ul>
				
				<div class="w-full">
					<div class="header-cart-total w-full p-tb-40">
						Total: $75.00
					</div>

					<div class="header-cart-buttons flex-w w-full">
						<a href="#" class="flex-c-m stext-101 cl0 size-107 bg3 bor2 hov-btn3 p-lr-15 trans-04 m-r-8 m-b-10">
							View Cart
						</a>

						<a href="#" class="flex-c-m stext-101 cl0 size-107 bg3 bor2 hov-btn3 p-lr-15 trans-04 m-b-10">
							Check Out
						</a>
					</div>
				</div>
			</div>
		</div>
	</div>


	<!-- breadcrumb -->
	<div class="container">
		<div class="bread-crumb flex-w p-l-25 p-r-15 p-t-30 p-lr-0-lg">
			<a href="#" class="stext-109 cl8 hov-cl1 trans-04">
				Home
				<i class="fa fa-angle-right m-l-9 m-r-10" aria-hidden="true"></i>
			</a>

			<span class="stext-109 cl4">
				Shoping Cart
			</span>
		</div>
	</div>
		

	<!-- Shoping Cart -->
	<form class="bg0 p-t-75 p-b-85">
		<div class="container">
			<div class="row">
				<div class="col-lg-10 col-xl-7 m-lr-auto m-b-50">
					<div class="m-l-25 m-r--38 m-lr-0-xl">
						<div class="wrap-table-shopping-cart">
							<table class="table-shopping-cart">
								<tr class="table_head">
									<th class="column-1">Image</th>
									<th class="column-2">Product</th>
									<th class="column-2">Color</th>
									<th class="column-3">Price</th>
									<th class="column-3">Discount</th>
									<th class="column-4">Quantity</th>
									<th class="column-5">Total</th>
								</tr>
                                {% for i in cart %}
								<tr class="table_row">
									<td class="column-1">
                                        <a href="{% url 'cart:delete' i.un_id %}">
										<div class="how-itemcart1">
                                            {% with i.product.images.all|first as f %}
											<img src="{{ f.image.url }}" alt="IMG">
                                            {% endwith %}
										</div>
                                        </a>
									</td>
                                    <td class="column-2"><a href="{{ i.product.get_absolute_url }}" class="text-dark">{{ i.product.title }}</a></td>
									<td class="column-2">{{ i.color }}</td>
									<td class="column-3">${{ i.product.price }}</td>
									<td class="column-3">%{{ i.product.discount }}</td>
									<td class="column-4">
										<div class="wrap-num-product flex-w m-l-auto m-r-0">
											<div class="btn-num-product-down cl8 hov-btn3 trans-04 flex-c-m">
												<i class="fs-16 zmdi zmdi-minus"></i>
											</div>

											<input class="mtext-104 cl3 txt-center num-product" type="number" name="num-product1" value="{{ i.quantity }}" min="1">

											<div class="btn-num-product-up cl8 hov-btn3 trans-04 flex-c-m">
												<i class="fs-16 zmdi zmdi-plus"></i>
											</div>
										</div>
									</td>
									<td class="column-5">${{ i.per_object_total }}</td>
								</tr>
                                {% endfor %}
							</table>
						</div>

						<div class="flex-w flex-sb-m bor15 p-t-18 p-b-15 p-lr-40 p-lr-15-sm">
							<div class="flex-w flex-m m-r-20 m-tb-5">
								<input class="stext-104 cl2 plh4 size-117 bor13 p-lr-20 m-r-10 m-tb-5" type="text" name="coupon" placeholder="Coupon Code">
									
								<div class="flex-c-m stext-101 cl2 size-118 bg8 bor13 hov-btn3 p-lr-15 trans-04 pointer m-tb-5">
									Apply coupon
								</div>
							</div>

							<div class="flex-c-m stext-101 cl2 size-119 bg8 bor13 hov-btn3 p-lr-15 trans-04 pointer m-tb-10">
								Update Cart
							</div>
						</div>
					</div>
				</div>

				<div class="col-sm-10 col-lg-7 col-xl-5 m-lr-auto m-b-50">
					<div class="bor10 p-lr-40 p-t-30 p-b-40 m-l-63 m-r-40 m-lr-0-xl p-lr-15-sm">
						<h4 class="mtext-109 cl2 p-b-30">
							Cart Totals
						</h4>

						<div class="flex-w flex-t bor12 p-b-13">
							<div class="size-208">
								<span class="stext-110 cl2">
									Subtotal:
								</span>
							</div>

							<div class="size-209">
								<span class="mtext-110 cl2">
									$79.65
								</span>
							</div>
						</div>

						<div class="flex-w flex-t p-t-27 p-b-33">
							<div class="size-208">
								<span class="mtext-101 cl2">
									Total:
								</span>
							</div>

							<div class="size-209 p-t-1">
								<span class="mtext-110 cl2">
									$79.65
								</span>
							</div>
						</div>

						<button class="flex-c-m stext-101 cl0 size-116 bg3 bor14 hov-btn3 p-lr-15 trans-04 pointer">
							Proceed to Checkout
						</button>
					</div>
				</div>
			</div>
		</div>
	</form>
{% endblock %}