accounts/urls.py
from django.urls import path
from accounts import views

app_name = 'accounts'
urlpatterns = [
    path('login', views.LoginView.as_view(), name='login'),
    path('logout', views.LogoutView.as_view(), name='logout'),
    path('register', views.RegisterView.as_view(), name='register'),
    path('create-account', views.CreateAccountView.as_view(), name='create-account'),
    path('change-password', views.ChangePasswordView.as_view(), name='change-password'),
    path('email-verify-g', views.GeneratorEmailVerifyView.as_view(), name='email-verify-g'),
    path('email-verify', views.EmailVerifyView.as_view(), name='email-verify'),
    path('forgot-pass', views.ForgotPassView.as_view(), name='forgot-pass'),
    path('forgot-password', views.EmailCheckView.as_view(), name='forgot-password'),
    path('resetpassword/<uidb64>/<str:token>', views.ResetPasswordView.as_view(), name='resetpassword'),
    path('setpassword', views.SetPasswordView.as_view(), name='setpassword'),
    path('forgotpassword', views.PhoneCheckView.as_view(), name='forgotpassword'),
    path('phone-authentication', views.CodeCheckView.as_view(), name='phone-authentication'),
    path('set-password', views.PHResetPasswordView.as_view(), name='set-password')
]

cart/urls.py
from django.urls import path
from cart import views

app_name = 'cart'
urlpatterns = [
    path('add/<int:id>', views.AddToCartView.as_view(), name='add'),
    path('delete/<str:un_id>', views.DeleteFromView.as_view(), name='delete'),
    path('', views.CartDetailView.as_view(), name='cart'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('products/', include('product.urls')),
    path('cart/', include('cart.urls')),
    path('', include('home.urls'))
] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/views.py
#accounts.apps
from accounts.models import *
from accounts.forms import *
from accounts.mixins import *

# django
from django.shortcuts import render, redirect
from django.views.generic import View, TemplateView
from django.contrib.auth import authenticate, login, logout
from django.db.models import Q
from django.contrib import messages
from django.urls import reverse
from django.utils.crypto import get_random_string


# django verification
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.core.mail import EmailMessage
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.shortcuts import get_current_site

# python
from random import randint


class LoginView(AnonymousRequiredMixin, View):

    def post(self, request):
        form = LoginForm(data=request.POST)
        if form.is_valid():
            cleaned_data = form.cleaned_data
            user = authenticate( # accounts/authentication.py
                username=cleaned_data['username'],
                password=cleaned_data['password']
            )
            if user is not None:
                login(request, user)
                messages.success(request, 'successfully login')
                return redirect('home:home')
            else:
                _user_object = User.objects.filter(
                    Q(username__exact=cleaned_data['username']) |
                    Q(email__exact=cleaned_data['username']) |
                    Q(phone__exact=cleaned_data['username'])
                ).first()
                if _user_object:
                    if _user_object.email == cleaned_data['username']:
                        form.add_error('username', 'invalid email or password')
                    elif _user_object.phone == cleaned_data['username']:
                        form.add_error('username', 'invalid phone or password')
                    elif _user_object.username == cleaned_data['username']:
                        form.add_error('username', 'invalid username or password')
                else:
                    form.add_error('username', 'user not found')
        return render(request, 'accounts/authenticate.html', context={'form':form})


    def get(self, request):
            context = {
                'form': LoginForm(),
            }
            return render(request, 'accounts/authenticate.html', context)


class RegisterView(AnonymousRequiredMixin, View):

    def post(self, request):
        form = RegisterForm(data=request.POST)
        if form.is_valid():
            cleaned_data = form.cleaned_data
            if not User.objects.filter(phone__exact=cleaned_data['phone']).exists():
                if OTPcheck.objects.filter(phone=cleaned_data['phone']).exists():
                    OTPcheck.objects.filter(phone=cleaned_data.get('phone')).delete()
                token, code = get_random_string(length=255), randint(1221, 9889)
                OTPcheck.objects.create(
                    code=code,
                    token=token,
                    phone=cleaned_data['phone']
                )
                request.session['phone'] = cleaned_data['phone']
                return redirect(reverse('accounts:create-account') + f'?token={token}')
            else:
                form.add_error('phone', 'this phone number is already exists')
        return render(request, 'accounts/authenticate.html', context={'form':form})


    def get(self, request):
            context = dict({
                'form': RegisterForm()
            })
            return render(request, 'accounts/authenticate.html', context)


class CreateAccountView(AnonymousRequiredMixin, View):

    def get(self, request):
        OTPcheck.otp_clean()
        if OTPcheck.objects.filter(
                Q(token__exact=request.GET.get('token')) &
                Q(phone=request.session['phone'])
        ).exists():
            form = OTPcheckForm()
            return render(request, 'accounts/authenticate.html', context={'form':form})
        else:
            return redirect('home:home')

    def post(self, request):
        OTPcheck.otp_clean()
        if OTPcheck.objects.filter(
            Q(token__exact=request.GET.get('token')) &
            Q(phone=request.session['phone'])
        ).exists():
            form = OTPcheckForm(data=request.POST)
            if form.is_valid():
                cleaned_data = form.cleaned_data
                if OTPcheck.objects.filter(code=cleaned_data['code'], phone=request.session['phone']).exists():
                    _user_object = User.objects.filter(
                        Q(username=cleaned_data['username']) |
                        Q(email=cleaned_data['email'])
                    )
                    if not _user_object.exists():
                        if cleaned_data['password1'] == cleaned_data['password2']:
                            User.objects.create_user(
                                username=cleaned_data['username'],
                                email=cleaned_data['email'],
                                phone=request.session['phone'],
                                password=cleaned_data['password1']
                            )
                            del request.session['phone']
                            OTPcheck.objects.filter(token=request.GET.get('token')).delete()
                            return redirect('accounts:login')
                        else:
                            form.add_error('password2', 'passwords does not match')
                    else:
                        q = _user_object.first()
                        if q.email == cleaned_data['email']:
                            form.add_error('email', 'this email is already exists')
                        if q.username == cleaned_data['username']:
                            form.add_error('username', 'this username is already exists')
                else:
                    form.add_error('code', 'invalid code')
            return render(request, 'accounts/authenticate.html', context={'form':form})
        else:
            return redirect('home:home')

class EmailCheckView(AnonymousRequiredMixin, View):

    def get(self, request):
        form = EmailCheckForm()
        return render(request, 'accounts/authenticate.html', context={'form':form})

    def post(self, request):
        form = EmailCheckForm(data=request.POST)
        if form.is_valid():
            cleaned_data = form.cleaned_data
            _user = User.objects.filter(Q(email=cleaned_data['email']))
            if _user.exists():
                user, subject = _user.first(), 'reset your password'
                EmailMessage(
                    subject,
                    render_to_string(
                        template_name='accounts/check_email.html',
                        context={
                            'user':user,
                            'domain':get_current_site(request),
                            'uid':urlsafe_base64_encode(force_bytes(user.pk)),
                            'token':default_token_generator.make_token(user)
                        }
                    ),
                    to=[user.email]
                ).send()
                messages.success(request, 'Password reset email has been sent to your email address')
                return redirect('accounts:login')
            else:
                form.add_error('email', 'this email is not exists')
            return render(request, 'accounts/authenticate.html', context={'form':form})
        else:
            return redirect('accounts:forgot-pass')

class ResetPasswordView(AnonymousRequiredMixin, View):

    def get(self, request, uidb64, token):
        try:
            u_id = urlsafe_base64_decode(uidb64).decode()
            user = User.objects.get(pk=u_id)
        except(User.DoesNotExist, ValueError, TypeError, OverflowError):
            user = None
        if user is not None and default_token_generator.check_token(user, token):
            request.session['uid'] = u_id
            messages.success(request, 'reset your password')
            return redirect('accounts:setpassword')
        else:
            messages.error(request, 'The link has been expired')
            return redirect('accounts:login')

class SetPasswordView(AnonymousRequiredMixin, View):

    def post(self, request):
        _user = User.objects.filter(Q(pk=request.session['uid']))
        if _user.exists():
            user = _user.first()
            form = SetPasswordForm(data=request.POST)
            if form.is_valid():
                cleaned_data = form.cleaned_data
                if cleaned_data['password1'] == cleaned_data['password2']:
                    user.set_password(cleaned_data.get('password1'))
                    user.save()
                    request.session.pop('uid', None)
                    messages.success(request, 'password reset successfully')
                    return redirect('accounts:login')
                else:
                    form.add_error('password1', 'password do not match')
            return render(request, 'accounts/authenticate.html', context={'form':form})
        else:
            return redirect('accounts:login')

    def get(self, request):
        if User.objects.filter(Q(pk=request.session['uid'])).exists():
            form = SetPasswordForm()
            return render(request, 'accounts/authenticate.html', context={'form':form})
        else:
            return redirect('accounts:login')

class PhoneCheckView(AnonymousRequiredMixin, View):

    def get(self, request):
        Auth2fa.clean_2fa()
        form = PhoneCheckForm()
        return render(request, 'accounts/authenticate.html', context={'form':form})

    def post(self, request):
        Auth2fa.clean_2fa()
        form = PhoneCheckForm(data=request.POST)
        if form.is_valid():

accounts/templates/accounts/authenticate.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %} {% if request.resolver_match.url_name == 'create-account' %} Register
{% elif request.resolver_match.url_name == 'change-password' %} Change Password
{% elif request.resolver_match.url_name == 'email-verify' %} Email Verification {% else %}
    {{ request.resolver_match.url_name|title }} {% endif %} {% endblock %}
{% block content %}
    <!-- authentication page -->
    <section class="bg0 p-t-104 p-b-116">
        <div class="container">
            <div class="flex-w flex-tr justify-content-center">
                <div class="size-210 bor10 p-lr-70 p-t-55 p-b-70 p-lr-15-lg w-full-md">
                    <form method="post">
                        {% csrf_token %}
                        <h4 class="mtext-105 cl2 txt-center p-b-30">
                            {% if request.resolver_match.url_name == 'create-account' %}
                                Register {% elif request.resolver_match.url_name == 'change-password' %} Change
                                Password {% elif request.resolver_match.url_name == 'email-verify' %} Email
                                Verification {% elif request.resolver_match.url_name == 'forgot-pass' %}
                                {% elif request.resolver_match.url_name == 'forgot-password' or request.resolver_match.url_name == 'forgotpassword' %}
                                Forgot Password {% else %} {{ request.resolver_match.url_name|title }} {% endif %}
                        </h4>
                        {% for field in form %}
                            {% if field.errors %}
                                <div class="text-danger small">{{ field.errors }}</div>
                            {% endif %}
                            <div class="bor8 m-b-20 how-pos4-parent">
                                {{ field }}
                            </div>
                        {% endfor %}
                        {% if request.resolver_match.url_name == 'login' %}
                            <a href="#">Forgot password</a> <br/>
                            <a href="#">Register</a>
                        {% elif request.resolver_match.url_name == 'register' %}
                            <a href="#">Login</a>
                        {% endif %}
                        {% if not request.resolver_match.url_name == 'forgot-pass' %}
                            <button class="flex-c-m stext-101 cl0 size-121 bg3 bor1 hov-btn3 p-lr-15 trans-04 pointer"
                                    style="margin-top: 20px">
                                {% if request.resolver_match.url_name == 'create-account' %}
                                    REGISTER {% elif request.resolver_match.url_name == 'change-password' %}
                                    Change {% elif request.resolver_match.url_name == 'email-verify' %}
                                    verify
                                    {% elif request.resolver_match.url_name == 'forgot-password' or request.resolver_match.url_name == 'forgotpassword' %}
                                    send {% else %} {{ request.resolver_match.url_name }} {% endif %}
                            </button>
                        {% else %}
                            <a href="{% url 'accounts:forgotpassword' %}"
                               class="flex-c-m stext-101 cl0 size-121 bg3 bor1 hov-btn3 p-lr-15 trans-04 pointer">Phone</a>
                            <a href="{% url 'accounts:forgot-password' %}"
                               class="flex-c-m stext-101 cl0 size-121 bg3 bor1 hov-btn3 p-lr-15 trans-04 pointer"
                               style="margin-top: 20px">Email</a>
                        {% endif %}
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

accounts/templates/accounts/check_email.html
{% autoescape off %}

Hi {{user.username}},

As requested, code for email verification.
http://{{ domain }}{% url 'accounts:resetpassword' uidb64=uid token=token %}

If you think it's not you, please ignore this email.

{% endautoescape %}

accounts/templates/accounts/verify_email.html
{% autoescape off %}

Hi {{user.username}},

As requested, code for email verification.
{{ code }}

If you think it's not you, please ignore this email.

{% endautoescape %}