cart/urls.py
from django.urls import path
from cart import views

app_name = 'cart'
urlpatterns = [
    path('add/<int:id>', views.AddToCartView.as_view(), name='add'),
    path('delete/<str:un_id>', views.DeleteFromView.as_view(), name='delete'),
    path('', views.CartDetailView.as_view(), name='cart'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('products/', include('product.urls')),
    path('cart/', include('cart.urls')),
    path('', include('home.urls'))
] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from home import views

app_name = 'home'
urlpatterns = (
    path('', views.HomeTemplateView.as_view(), name='home'),
    path('render_partial_for_objects_view', views.render_partial_for_objects_view, name='render_partial_for_objects_view'),

)

product/urls.py
from django.urls import path
from . import views

app_name = 'product'
urlpatterns = [
    path('detail/<slug:slug>', views.ProductDetailView.as_view(), name='detail'),
    path('like/<slug:slug>/<int:id>', views.like, name='like'),
    path('', views.products, name='products')
]

cart/models.py
from django.db import models
from product.models import Product

class Cart:

    def __new__(cls, *args, **kwargs):
        return super().__new__(cls)

    def __init__(self, request):
        self.session = request.session
        self.cart = self.session.get('cart')
        if not self.cart:
            self.cart = self.session['cart'] = dict()

    def __iter__(self):
        cart = self.cart
        for i in cart.values():
            i['product'] = un_id = Product.objects.get(pk=int(i['id']))
            i['total'] = (int(i['quantity']) * float(i['price']))
            i['un_id'] = self.unique_id_generator(id=un_id.id, color=i['color'])
            if 0 < float(i['discount']):
                i['per_object_total'] = (
                    i['total'] - ((float(i['total']) - float(i['discount'])) / 100)
                )
            yield i

    def add(self, product, quantity, color):
        unique = self.unique_id_generator(id=product.id, color=color)
        if not unique in self.cart:
            self.cart[unique] = dict({
                'id': str(product.id),
                'price': str(product.price),
                'discount': str(product.discount),
                'color':color,
                'quantity': int(quantity),
            })
            self.save()
        else:
            self.cart[unique]['quantity'] += int(quantity)
            self.save()

    def delete(self, un_id):
        if self.cart[un_id]:
            del self.cart[un_id]
            self.save()

    def remove_cart(self):
        del self.session['cart']

    def save(self):
        self.session.modified = True

    @staticmethod
    def unique_id_generator(id, color):
        return f"{id}{color}"

cart/views.py
from django.shortcuts import render, redirect
from django.views.generic.detail import DetailView
from django.views.generic import View
from cart.models import *
from product.models import Product

class CartDetailView(View):
    template_name = 'cart/cart.html'

    def get(self, request):
        cart = Cart(self.request)
        return render(request, self.template_name, context={'cart':cart})


class AddToCartView(View):

    def post(self, request, id):
        product = Product.objects.get(pk=id)
        quantity, color = self.request.POST.get('quantity'), self.request.POST.get('color')
        print(quantity, color, product.title)
        Cart(self.request).add(product, quantity, color)
        return redirect('product:detail', product.slug)


class DeleteFromView(View):

    def get(self, request, un_id):
        Cart(self.request).delete(un_id=un_id)
        return redirect('cart:cart')

templates/includes/cart.html
{% load static %}
<div class="wrap-header-cart js-panel-cart">
		<div class="s-full js-hide-cart"></div>

		<div class="header-cart flex-col-l p-l-65 p-r-25">
			<div class="header-cart-title flex-w flex-sb-m p-b-8">
				<span class="mtext-103 cl2">
					Your Cart
				</span>

				<div class="fs-35 lh-10 cl2 p-lr-5 pointer hov-cl1 trans-04 js-hide-cart">
					<i class="zmdi zmdi-close"></i>
				</div>
			</div>

			<div class="header-cart-content flex-w js-pscroll">
				<ul class="header-cart-wrapitem w-full">
					<li class="header-cart-item flex-w flex-t m-b-12">
						<div class="header-cart-item-img">
							<img src="{% static 'images/item-cart-01.jpg' %}" alt="IMG">
						</div>

						<div class="header-cart-item-txt p-t-8">
							<a href="#" class="header-cart-item-name m-b-18 hov-cl1 trans-04">
								White Shirt Pleat
							</a>

							<span class="header-cart-item-info">
								1 x $19.00
							</span>
						</div>
					</li>

					<li class="header-cart-item flex-w flex-t m-b-12">
						<div class="header-cart-item-img">
							<img src="{% static 'images/item-cart-02.jpg' %}" alt="IMG">
						</div>

						<div class="header-cart-item-txt p-t-8">
							<a href="#" class="header-cart-item-name m-b-18 hov-cl1 trans-04">
								Converse All Star
							</a>

							<span class="header-cart-item-info">
								1 x $39.00
							</span>
						</div>
					</li>

					<li class="header-cart-item flex-w flex-t m-b-12">
						<div class="header-cart-item-img">
							<img src="{% static 'images/item-cart-03.jpg' %}" alt="IMG">
						</div>

						<div class="header-cart-item-txt p-t-8">
							<a href="#" class="header-cart-item-name m-b-18 hov-cl1 trans-04">
								Nixon Porter Leather
							</a>

							<span class="header-cart-item-info">
								1 x $17.00
							</span>
						</div>
					</li>
				</ul>

				<div class="w-full">
					<div class="header-cart-total w-full p-tb-40">
						Total: $75.00
					</div>

					<div class="header-cart-buttons flex-w w-full">
						<a href="#" class="flex-c-m stext-101 cl0 size-107 bg3 bor2 hov-btn3 p-lr-15 trans-04 m-r-8 m-b-10">
							View Cart
						</a>

						<a href="#" class="flex-c-m stext-101 cl0 size-107 bg3 bor2 hov-btn3 p-lr-15 trans-04 m-b-10">
							Check Out
						</a>
					</div>
				</div>
			</div>
		</div>
	</div>

templates/includes/filter_search.html
{% load static %}
<div class="flex-w flex-sb-m p-b-52">
				<div class="flex-w flex-l-m filter-tope-group m-tb-10">
                    {% if request.resolver_match.url_name == 'home' %}
					<button class="stext-106 cl6 hov1 bor3 trans-04 m-r-32 m-tb-5 how-active1" data-filter="*">
						All Products
					</button>

					<button class="stext-106 cl6 hov1 bor3 trans-04 m-r-32 m-tb-5" data-filter=".16thgenerationiPhone">
						16th generation iPhone
					</button>

					<button class="stext-106 cl6 hov1 bor3 trans-04 m-r-32 m-tb-5" data-filter=".macbook">
						macbook
					</button>

					<button class="stext-106 cl6 hov1 bor3 trans-04 m-r-32 m-tb-5" data-filter=".airpod">
						airpod
					</button>
                    {% endif %}
				</div>

				<div class="flex-w flex-c-m m-tb-10">
					<div class="flex-c-m stext-106 cl6 size-104 bor4 pointer hov-btn3 trans-04 m-r-8 m-tb-4 js-show-filter">
						<i class="icon-filter cl2 m-r-6 fs-15 trans-04 zmdi zmdi-filter-list"></i>
						<i class="icon-close-filter cl2 m-r-6 fs-15 trans-04 zmdi zmdi-close dis-none"></i>
						 Filter
					</div>

					<div class="flex-c-m stext-106 cl6 size-105 bor4 pointer hov-btn3 trans-04 m-tb-4 js-show-search">
						<i class="icon-search cl2 m-r-6 fs-15 trans-04 zmdi zmdi-search"></i>
						<i class="icon-close-search cl2 m-r-6 fs-15 trans-04 zmdi zmdi-close dis-none"></i>
						Search
					</div>
				</div>

				<!-- Search product -->
				<div class="dis-none panel-search w-full p-t-10 p-b-15">
					<div class="bor8 dis-flex p-l-15">
						<button class="size-113 flex-c-m fs-16 cl2 hov-cl1 trans-04">
							<i class="zmdi zmdi-search"></i>
						</button>

						<input class="mtext-107 cl2 size-114 plh2 p-r-15" type="text" name="search-product" placeholder="Search">
					</div>
				</div>

				<!-- Filter -->
				<div class="dis-none panel-filter w-full p-t-10">
					<div class="wrap-filter flex-w bg6 w-full p-lr-40 p-t-27 p-lr-15-sm">
						<div class="filter-col1 p-r-15 p-b-27">
							<div class="mtext-102 cl2 p-b-15">
								Sort By
							</div>

							<ul>

								<li class="p-b-6">
									<a href="{% url 'product:products' %}?sort=new{% if request.GET.color %}&color={{ request.GET.color }}{% endif %}{% if request.GET.aprice and request.GET.bprice %}&aprice={{ request.GET.aprice }}&bprice={{ request.GET.bprice }}{% endif %}" class="filter-link stext-106 trans-04 filter-link-active">
										Newness
									</a>
								</li>

								<li class="p-b-6">
									<a href="{% url 'product:products' %}?sort=low-to-high{% if request.GET.color %}&color={{ request.GET.color }}{% endif %}{% if request.GET.aprice and request.GET.bprice %}&aprice={{ request.GET.aprice }}&bprice={{ request.GET.bprice }}{% endif %}" class="filter-link stext-106 trans-04">
										Price: Low to High
									</a>
								</li>

								<li class="p-b-6">
                                    <a href="{% url 'product:products' %}?sort=high-to-low{% if request.GET.color %}&color={{ request.GET.color }}{% endif %}{% if request.GET.aprice and request.GET.bprice %}&aprice={{ request.GET.aprice }}&bprice={{ request.GET.bprice }}{% endif %}" class="filter-link stext-106 trans-04">
										Price: High to Low
									</a>
								</li>
							</ul>
						</div>

						<div class="filter-col2 p-r-15 p-b-27">
							<div class="mtext-102 cl2 p-b-15">
								Price
							</div>

							<ul>
								<li class="p-b-6">
									<a href="" class="filter-link stext-106 trans-04 {% if not request.GET.aprice or not request.GET.bprice %}filter-link-active {% endif %}">
										All
									</a>
								</li>
                                {% for i in pricerange %}
								<li class="p-b-6">
									<a href="{% url 'product:products' %}?aprice={{ i.a }}&bprice={{ i.b }}{% if request.GET.color %}&color={{ request.GET.color }}{% endif %}{% if request.GET.sort %}&sort={{ request.GET.sort }}{% endif %}" class="filter-link stext-106 trans-04 {% if request.GET.aprice == i.a_to_str %}filter-link-active{% endif %}">
										${{ i.a }}0 - ${{ i.b }}0
									</a>

								</li>
                                {% endfor %}
							</ul>
						</div>

						<div class="filter-col3 p-r-15 p-b-27">
							<div class="mtext-102 cl2 p-b-15">
								Color
							</div>

							<ul>
                                {% for i in colors %}
								<li class="p-b-6">
									<span class="fs-15 lh-12 m-r-6" style="color: #{{ i.color_code }};">
										<i class="zmdi zmdi-circle"></i>
									</span>

									<a href="{% url 'product:products' %}?color={{ i.title }}{% if request.GET.aprice and request.GET.bprice %}&aprice={{ request.GET.aprice }}&bprice={{ request.GET.bprice }}{% endif %}{% if request.GET.sort %}&sort={{ request.GET.sort }}{% endif %}" class="filter-link stext-106 trans-04 {% if request.GET.color == i.title %}filter-link-active {% endif %}">
										{{ i.title }}
									</a>
								</li>
                                {% endfor %}
							</ul>
						</div>

					</div>
				</div>
			</div>

templates/includes/footer.html
{% load static %}
	<footer class="bg3 p-t-75 p-b-32">
		<div class="container">
			<div class="row">
				<div class="col-sm-6 col-lg-3 p-b-50">
					<h4 class="stext-301 cl0 p-b-30">
						Categories
					</h4>

					<ul>
						<li class="p-b-10">
							<a href="#" class="stext-107 cl7 hov-cl1 trans-04">
								Women
							</a>
						</li>

						<li class="p-b-10">
							<a href="#" class="stext-107 cl7 hov-cl1 trans-04">
								Men
							</a>
						</li>

						<li class="p-b-10">
							<a href="#" class="stext-107 cl7 hov-cl1 trans-04">
								Shoes
							</a>
						</li>

						<li class="p-b-10">
							<a href="#" class="stext-107 cl7 hov-cl1 trans-04">
								Watches
							</a>
						</li>
					</ul>
				</div>

				<div class="col-sm-6 col-lg-3 p-b-50">
					<h4 class="stext-301 cl0 p-b-30">
						Help
					</h4>

					<ul>
						<li class="p-b-10">
							<a href="#" class="stext-107 cl7 hov-cl1 trans-04">
								Track Order
							</a>
						</li>

						<li class="p-b-10">
							<a href="#" class="stext-107 cl7 hov-cl1 trans-04">
								Returns
							</a>
						</li>

						<li class="p-b-10">
							<a href="#" class="stext-107 cl7 hov-cl1 trans-04">
								Shipping
							</a>
						</li>

						<li class="p-b-10">
							<a href="#" class="stext-107 cl7 hov-cl1 trans-04">
								FAQs
							</a>
						</li>
					</ul>
				</div>

				<div class="col-sm-6 col-lg-3 p-b-50">
					<h4 class="stext-301 cl0 p-b-30">
						GET IN TOUCH
					</h4>

					<p class="stext-107 cl7 size-201">
						Any questions? Let us know in store at 8th floor, 379 Hudson St, New York, NY 10018 or call us on (+1) 96 716 6879
					</p>

					<div class="p-t-27">
						<a href="#" class="fs-18 cl7 hov-cl1 trans-04 m-r-16">
							<i class="fa fa-facebook"></i>
						</a>

						<a href="#" class="fs-18 cl7 hov-cl1 trans-04 m-r-16">
							<i class="fa fa-instagram"></i>
						</a>

						<a href="#" class="fs-18 cl7 hov-cl1 trans-04 m-r-16">
							<i class="fa fa-pinterest-p"></i>
						</a>
					</div>
				</div>

				<div class="col-sm-6 col-lg-3 p-b-50">
					<h4 class="stext-301 cl0 p-b-30">
						Newsletter
					</h4>

					<form>
						<div class="wrap-input1 w-full p-b-4">
							<input class="input1 bg-none plh1 stext-107 cl7" type="text" name="email" placeholder="email@example.com">
							<div class="focus-input1 trans-04"></div>
						</div>

						<div class="p-t-18">
							<button class="flex-c-m stext-101 cl0 size-103 bg1 bor1 hov-btn2 p-lr-15 trans-04">
								Subscribe
							</button>
						</div>
					</form>
				</div>
			</div>

			<div class="p-t-40">
				<div class="flex-c-m flex-w p-b-18">
					<a href="#" class="m-all-1">
						<img src="{% static 'images/icons/icon-pay-01.png'%}" alt="ICON-PAY">
					</a>

					<a href="#" class="m-all-1">
						<img src="{% static 'images/icons/icon-pay-02.png'%}" alt="ICON-PAY">
					</a>

					<a href="#" class="m-all-1">
						<img src="{% static 'images/icons/icon-pay-03.png'%}" alt="ICON-PAY">
					</a>

					<a href="#" class="m-all-1">
						<img src="{% static 'images/icons/icon-pay-04.png'%}" alt="ICON-PAY">
					</a>

					<a href="#" class="m-all-1">
						<img src="{% static 'images/icons/icon-pay-05.png'%}" alt="ICON-PAY">
					</a>
				</div>

				<p class="stext-107 cl6 txt-center">
					<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | Made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a> &amp; distributed by <a href="https://themewagon.com" target="_blank">ThemeWagon</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->

				</p>
			</div>
		</div>
	</footer>

templates/includes/footer_references.html
{% load static %}
<!--===============================================================================================-->
	<script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/select2/select2.min.js' %}"></script>
	<script>
		$(".js-select2").each(function(){
			$(this).select2({
				minimumResultsForSearch: 20,
				dropdownParent: $(this).next('.dropDownSelect2')
			});
		})
	</script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{% static 'vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/slick/slick.min.js' %}"></script>
	<script src="{% static 'js/slick-custom.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/parallax100/parallax100.js' %}"></script>
	<script>
        $('.parallax100').parallax100();
	</script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/MagnificPopup/jquery.magnific-popup.min.js' %}"></script>
	<script>
		$('.gallery-lb').each(function() { // the containers for all your galleries
			$(this).magnificPopup({
		        delegate: 'a', // the selector for gallery item
		        type: 'image',
		        gallery: {
		        	enabled:true
		        },
		        mainClass: 'mfp-fade'
		    });
		});
	</script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/isotope/isotope.pkgd.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/sweetalert/sweetalert.min.js' %}"></script>
	<script>
		$('.js-addwish-b2').on('click', function(e){
			e.preventDefault();
		});

		$('.js-addwish-b2').each(function(){
			var nameProduct = $(this).parent().parent().find('.js-name-b2').html();
			$(this).on('click', function(){
				swal(nameProduct, "is added to wishlist !", "success");

				$(this).addClass('js-addedwish-b2');
				$(this).off('click');
			});
		});

		$('.js-addwish-detail').each(function(){
			var nameProduct = $(this).parent().parent().parent().find('.js-name-detail').html();

			$(this).on('click', function(){
				swal(nameProduct, "is added to wishlist !", "success");

				$(this).addClass('js-addedwish-detail');
				$(this).off('click');
			});
		});

		/*---------------------------------------------*/

		$('.js-addcart-detail').each(function(){
			var nameProduct = $(this).parent().parent().parent().parent().find('.js-name-detail').html();
			$(this).on('click', function(){
				swal(nameProduct, "is added to cart !", "success");
			});
		});

	</script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/perfect-scrollbar/perfect-scrollbar.min.js' %}"></script>
	<script>
		$('.js-pscroll').each(function(){
			$(this).css('position','relative');
			$(this).css('overflow','hidden');
			var ps = new PerfectScrollbar(this, {
				wheelSpeed: 1,
				scrollingThreshold: 1000,
				wheelPropagation: false,
			});

			$(window).on('resize', function(){
				ps.update();
			})
		});
	</script>
<!--===============================================================================================-->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>

    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/ajax.js' %}"></script>

templates/includes/head_references.html
{% load static %}
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="{% static 'images/icons/favicon.png' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/iconic/css/material-design-iconic-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/linearicons-v1.0.0/icon-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animsition/css/animsition.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/daterangepicker/daterangepicker.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/slick/slick.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/MagnificPopup/magnific-popup.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/perfect-scrollbar/perfect-scrollbar.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
<!--===============================================================================================-->

templates/includes/header.html
{% load static %}
{% load tags %}
<header>
		<!-- Header desktop -->
		<div class="container-menu-desktop">
			<!-- Topbar -->
			<div class="top-bar">
				<div class="content-topbar flex-sb-m h-full container">
					<div class="left-top-bar">
						Free shipping for standard order over $100
					</div>

					<div class="right-top-bar flex-w h-full">
						<a href="#" class="flex-c-m trans-04 p-lr-25">
							Help & FAQs
						</a>

						<a href="#" class="flex-c-m trans-04 p-lr-25">
							My Account
						</a>

						<a href="#" class="flex-c-m trans-04 p-lr-25">
							EN
						</a>

						<a href="#" class="flex-c-m trans-04 p-lr-25">
							USD
						</a>
					</div>
				</div>
			</div>

			<div class="wrap-menu-desktop">
				<nav class="limiter-menu-desktop container">

					<!-- Logo desktop -->
					<a href="{% url 'home:home' %}" class="logo">
						<img src="{% static 'images/Apple_logo_grey.svg' %}" height="40px" alt="IMG-LOGO">
					</a>

					<!-- Menu desktop -->
					<div class="menu-desktop">
						<ul class="main-menu">
							<li class="active-menu">
								<a href="#">Home</a>
								<ul class="sub-menu">
									<li><a href="#">Homepage 1</a></li>
									<li><a href="#">Homepage 2</a></li>
									<li><a href="#">Homepage 3</a></li>
								</ul>
							</li>

							<li>
								<a href="#">Shop</a>
							</li>

							<li class="label1" data-label1="hot">
								<a href="#">Features</a>
							</li>

							<li>
								<a href="#">Blog</a>
							</li>

							<li>
								<a href="#">About</a>
							</li>

							<li>
								<a href="#">Contact</a>
							</li>
						</ul>
					</div>

					<!-- Icon header -->
					<div class="wrap-icon-header flex-w flex-r-m">
						<div class="icon-header-item cl2 hov-cl1 trans-04 p-l-22 p-r-11 js-show-modal-search">
							<i class="zmdi zmdi-search"></i>
						</div>

						<div class="icon-header-item cl2 hov-cl1 trans-04 p-l-22 p-r-11 icon-header-noti" data-notify="{% cart_counter request %}">
							<a href="{% url 'cart:cart' %}" class="text-dark"><i class="zmdi zmdi-shopping-cart"></i></a>
						</div>

					</div>
				</nav>
			</div>
		</div>

		<!-- Header Mobile -->
		<div class="wrap-header-mobile">
			<!-- Logo moblie -->
			<div class="logo-mobile">
				<a href="#"><img src="{% static 'images/icons/logo-01.png' %}" alt="IMG-LOGO"></a>
			</div>

			<!-- Icon header -->
			<div class="wrap-icon-header flex-w flex-r-m m-r-15">
				<div class="icon-header-item cl2 hov-cl1 trans-04 p-r-11 js-show-modal-search">
					<i class="zmdi zmdi-search"></i>
				</div>

				<div class="icon-header-item cl2 hov-cl1 trans-04 p-r-11 p-l-10 icon-header-noti" data-notify="{% cart_counter request %}">
					<i class="zmdi zmdi-shopping-cart"></i>
				</div>

			</div>

			<!-- Button show menu -->
			<div class="btn-show-menu-mobile hamburger hamburger--squeeze">
				<span class="hamburger-box">
					<span class="hamburger-inner"></span>
				</span>
			</div>
		</div>


		<!-- Menu Mobile -->
		<div class="menu-mobile">
			<ul class="topbar-mobile">
				<li>
					<div class="left-top-bar">
						Free shipping for standard order over $100
					</div>
				</li>

				<li>
					<div class="right-top-bar flex-w h-full">
						<a href="#" class="flex-c-m p-lr-10 trans-04">
							Help & FAQs
						</a>

						<a href="#" class="flex-c-m p-lr-10 trans-04">
							My Account
						</a>

						<a href="#" class="flex-c-m p-lr-10 trans-04">
							EN
						</a>

						<a href="#" class="flex-c-m p-lr-10 trans-04">
							USD
						</a>
					</div>
				</li>
			</ul>

			<ul class="main-menu-m">
				<li>
					<a href="#l">Home</a>
					<ul class="sub-menu-m">
						<li><a href="#">Homepage 1</a></li>
						<li><a href="#">Homepage 2</a></li>
						<li><a href="#">Homepage 3</a></li>
					</ul>
					<span class="arrow-main-menu-m">
						<i class="fa fa-angle-right" aria-hidden="true"></i>
					</span>
				</li>

				<li>
					<a href="#">Shop</a>
				</li>

				<li>
					<a href="#" class="label1 rs1" data-label1="hot">Features</a>
				</li>

				<li>
					<a href="#">Blog</a>
				</li>

				<li>
					<a href="#">About</a>
				</li>

				<li>
					<a href="#">Contact</a>
				</li>
			</ul>
		</div>

		<!-- Modal Search -->
		<div class="modal-search-header flex-c-m trans-04 js-hide-modal-search">
			<div class="container-search-header">
				<button class="flex-c-m btn-hide-modal-search trans-04 js-hide-modal-search">
					<img src="{% static 'images/icons/icon-close2.png' %}" alt="CLOSE">
				</button>

				<form class="wrap-search-header flex-w p-l-15">
					<button class="flex-c-m trans-04">
						<i class="zmdi zmdi-search"></i>
					</button>
					<input class="plh3" type="text" name="search" placeholder="Search..." aria-label="#"/>
				</form>
			</div>
		</div>
	</header>